/*
 * This source file was generated by the Gradle 'init' task
 */
package org.thumbgen;

import org.apache.commons.io.FilenameUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.Objects;

import static org.apache.commons.io.FilenameUtils.indexOfExtension;
import static org.apache.logging.log4j.core.util.internal.Status.NOT_FOUND;
import static org.junit.jupiter.api.Assertions.*;

class ThumbGenTest {

    private static final String[] GENERATED_FILE_EXTENSION = new String[]{"png"};

    @BeforeAll
    public static void init(){
        File folder = new File("src/test/resources");
        System.out.println("INIT");

        for (File f : Objects.requireNonNull(folder.listFiles())) {
            if (Arrays.asList(GENERATED_FILE_EXTENSION).contains(FilenameUtils.getExtension(f.getName()))) {
                System.out.println("Deleted: " + f.getName());
                f.delete(); // may fail mysteriously - returns boolean you may want to check
            }
        }
    }

    @Test void generatePptImage() throws IOException {
        ThumbGen testClass = new ThumbGen();
        testClass.main(new String[]{"src/test/resources/doc1.ppt"});
        File file = new File("src/test/resources/doc1.ppt-thumbnail.png");
        assertTrue(file.exists());
    }

    @Test void generatePptxImage() throws IOException {
        ThumbGen testClass = new ThumbGen();
        testClass.main(new String[]{"src/test/resources/doc2.pptx"});
        File file = new File("src/test/resources/doc2.pptx-thumbnail.png");
        assertTrue(file.exists());
    }

    @Test void generatePptxUpperCaseImage() throws IOException {
        ThumbGen testClass = new ThumbGen();
        testClass.main(new String[]{"src/test/resources/doc3.PPTX"});
        File file = new File("src/test/resources/doc3.PPTX-thumbnail.png");
        assertTrue(file.exists());
    }

    @Test void generatePptUpperCaseImage() throws IOException {
        ThumbGen testClass = new ThumbGen();
        testClass.main(new String[]{"src/test/resources/doc4.PPT"});
        File file = new File("src/test/resources/doc4.PPT-thumbnail.png");
        assertTrue(file.exists());
    }
}
